// Code generated by app-config; DO NOT EDIT.

package config

type BaseConfig struct {
	Persistence Persistence `koanf:"persistence"`
	Views       Views       `koanf:"views"`
}

type Persistence struct {
	DSN                   string `koanf:"dsn"`
}

type Views struct {
	CSSPath          string `koanf:"css_path"`
	DirFS            string `koanf:"dir_fs"`
	DirOS            string `koanf:"dir_os"`
	JSPath           string `koanf:"js_path"`
}
