// Code generated by app-config; DO NOT EDIT.

package appconfig_complex

type Config struct {
	Database Database `koanf:"database"`
	Auth     Auth     `koanf:"auth"`
	Views    Views    `koanf:"views"`
}

type Auth struct {
	Enabled bool   `koanf:"enabled"`
	Users   []User `koanf:"users"`
}

type User struct {
	Username string `koanf:"username"`
	Password string `koanf:"password"`
}

type Views struct {
	Dir       string `koanf:"dir"`
	Extension string `koanf:"extension"`
}

type Database struct {
	Dsn    string `koanf:"dsn"`
	Debug  bool   `koanf:"debug"`
	Driver string `koanf:"driver"`
	Server string `koanf:"server"`
}
