// Code generated by options-setters; DO NOT EDIT.

package multi

import (
	http "http"
	"io"
	"time"
)

type WriterGetter interface {
	GetWriter() io.Writer
}

func WithWriterSetter(s WriterGetter) Option {
	return func(cs *Config) {
		if s != nil {
			cs.writer = s.GetWriter()
		}
	}
}

type ClientGetter interface {
	GetClient() *http.Client
}

func WithClientSetter(s ClientGetter) Option {
	return func(cs *Config) {
		if s != nil {
			cs.client = s.GetClient()
		}
	}
}

type DeadlineGetter interface {
	GetDeadline() time.Time
}

func WithDeadlineSetter(s DeadlineGetter) Option {
	return func(cs *Config) {
		if s != nil {
			cs.deadline = s.GetDeadline()
		}
	}
}

// WithConfigurator sets multiple options from
// a single configuration struct that implements
// one or more Getter interfaces
func WithConfigurator(i interface{}) Option {
	return func(cs *Config) {

		if s, ok := i.(WriterGetter); ok {
			cs.writer = s.GetWriter()
		}

		if s, ok := i.(ClientGetter); ok {
			cs.client = s.GetClient()
		}

		if s, ok := i.(DeadlineGetter); ok {
			cs.deadline = s.GetDeadline()
		}

	}
}
