// Code generated by app-config; DO NOT EDIT.

package appconfig

import fs "fs"

type Config struct {
	Database Database `koanf:"database"`
}

type Database struct {
	AssetsFS fs.FS  `koanf:"assets_fs"`
	DSN      string `koanf:"dsn"`
}

func (d *Database) SetAssetsFS(val fs.FS) {
	d.AssetsFS = val
}
