// Code generated by app-config; DO NOT EDIT.

package appconfig

type Config struct {
	Database Database `koanf:"database"`
}

type Database struct {
	Debug      bool   `koanf:"debug"`
	DefaultTTL string `koanf:"default_ttl"`
	Driver     string `koanf:"driver"`
	Dsn        string `koanf:"dsn"`
	Server     string `koanf:"server"`
}
