// Code generated by options-setters; DO NOT EDIT.

package basic

type NameGetter interface {
	GetName() string
}

func WithNameSetter(s NameGetter) Option {
	return func(cs *Config) {
		if s != nil {
			cs.name = s.GetName()
		}
	}
}

type ValueGetter interface {
	GetValue() int
}

func WithValueSetter(s ValueGetter) Option {
	return func(cs *Config) {
		if s != nil {
			cs.value = s.GetValue()
		}
	}
}

// WithConfigurator sets multiple options from
// a single configuration struct that implements
// one or more Getter interfaces
func WithConfigurator(i interface{}) Option {
	return func(cs *Config) {

		if s, ok := i.(NameGetter); ok {
			cs.name = s.GetName()
		}

		if s, ok := i.(ValueGetter); ok {
			cs.value = s.GetValue()
		}

	}
}
