// Code generated by app-config; DO NOT EDIT.

package main

type TOMLConfig struct {
	Auth     Auth     `json:"auth" koanf:"auth"`
	Database Database `json:"database" koanf:"database"`
	Views    Views    `json:"views" koanf:"views"`
}

type Auth struct {
	Enabled    bool   `json:"enabled" koanf:"enabled"`
	SessionTTL string `json:"session_ttl" koanf:"session_ttl"`
	Users      any    `json:"users" koanf:"users"`
}

type Database struct {
	Debug  bool   `json:"debug" koanf:"debug"`
	Driver string `json:"driver" koanf:"driver"`
	Dsn    string `json:"dsn" koanf:"dsn"`
	Server string `json:"server" koanf:"server"`
}

type Views struct {
	Dir           string `json:"dir" koanf:"dir"`
	FileExtension string `json:"file_extension" koanf:"file_extension"`
}
