// Code generated by app-config; DO NOT EDIT.

package main

type Config struct {
	Auth     Auth     `koanf:"auth"`
	Database Database `koanf:"database"`
	Views    Views    `koanf:"views"`
}

type Auth struct {
	Enabled    bool   `koanf:"enabled"`
	SessionTTL string `koanf:"session_ttl"`
	Users      []User `koanf:"users"`
}

type Database struct {
	Debug  bool   `koanf:"debug"`
	Driver string `koanf:"driver"`
	Dsn    string `koanf:"dsn"`
	Server string `koanf:"server"`
}

type User struct {
	Password string `koanf:"password"`
	Username string `koanf:"username"`
}

type Views struct {
	Dir           string `koanf:"dir"`
	FileExtension string `koanf:"file_extension"`
}
